import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Lightbulb, ArrowRight, CheckCircle2, AlertTriangle, Info, Sparkles, Loader2, Inbox, Trash2, Check } from 'lucide-react';
import { api } from '../services/api';
import type { Recommendation } from '../services/api';

export const Recommendations: React.FC = () => {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [toasts, setToasts] = useState<{ id: number; message: string; type?: 'success' | 'info' }[]>([]);

  const addToast = (message: string, type: 'success' | 'info' = 'success') => {
    const id = Date.now();
    setToasts(prev => [...prev, { id, message, type }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 4000);
  };

  // Fetch recommendations from API
  const fetchRecommendations = async (silent = false) => {
    if (!silent) setLoading(true);
    try {
      const data = await api.getRecommendations();
      setRecommendations(data);
    } catch (err) {
      console.error(err);
    } finally {
      if (!silent) setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  // Handle Apply Recommendation
  const handleApply = async (id: string | undefined, title: string) => {
    if (!id) return;
    try {
      const response = await api.applyRecommendation(id, title);
      setRecommendations(prev => prev.filter(r => (r.id || r._id) !== id));
      addToast(`Action implemented successfully: "${title}". Generated PO: ${response.po_id || 'N/A'}`);
    } catch (err) {
      addToast('Failed to apply recommendation.', 'info');
    }
  };

  // Handle Dismiss Recommendation
  const handleDismiss = (id: string | undefined, title: string) => {
    if (!id) return;
    setRecommendations(prev => prev.filter(r => (r.id || r._id) !== id));
    addToast(`Archived suggestion: "${title}"`, 'info');
  };

  // Handle Regenerate Recommendations
  const handleRegenerate = async () => {
    if (regenerating) return;
    setRegenerating(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 1500));
      await fetchRecommendations(true);
      addToast("Recalculated full inventory vector. Suggestions updated!", 'success');
    } catch (err) {
      addToast('Error communicating with deep inference model.', 'info');
    } finally {
      setRegenerating(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto relative">
      {/* Toast Overlay */}
      <div className="fixed bottom-6 right-6 z-50 space-y-3 pointer-events-none">
        <AnimatePresence>
          {toasts.map(toast => (
            <motion.div
              key={toast.id}
              initial={{ opacity: 0, y: 30, scale: 0.9 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9, y: -20 }}
              className={`backdrop-blur-xl border p-4 rounded-2xl shadow-2xl flex items-center gap-3 text-sm font-medium pointer-events-auto min-w-[300px] ${
                toast.type === 'info' ? 'bg-blue-500/15 border-blue-500/20 text-blue-400' :
                'bg-emerald-500/15 border-emerald-500/20 text-emerald-400'
              }`}
            >
              <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                toast.type === 'info' ? 'bg-blue-500/20 text-blue-500' : 'bg-emerald-500/20 text-emerald-500'
              }`}>
                {toast.type === 'info' ? <Trash2 className="w-4 h-4" /> : <Check className="w-4 h-4" />}
              </div>
              <p className="flex-1 text-foreground">{toast.message}</p>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">AI Recommendations</h1>
          <p className="text-sm text-foreground/50 mt-1">Actionable insights generated by Pro Vision AI Engine v2.4</p>
        </div>
        <button 
          onClick={handleRegenerate}
          disabled={regenerating || loading}
          className="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl text-sm font-medium shadow-lg shadow-primary/20 transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50"
        >
          {regenerating ? (
            <>
              <Loader2 className="w-4.5 h-4.5 animate-spin" />
              <span>Inference Running...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-4.5 h-4.5" />
              <span>Regenerate Suggestions</span>
            </>
          )}
        </button>
      </div>

      {loading ? (
        <div className="h-[400px] w-full bg-card border border-border rounded-2xl flex items-center justify-center">
          <Loader2 className="w-8 h-8 text-primary animate-spin" />
        </div>
      ) : (
        <div className="grid gap-4">
          <AnimatePresence mode="popLayout">
            {recommendations.length > 0 ? (
              recommendations.map((rec) => {
                const recId = rec.id || rec._id;
                const recConfidence = rec.confidence || 95;
                const recImpact = rec.impact || "High Efficiency";
                return (
                  <motion.div
                    key={recId}
                    layoutId={`rec-${recId}`}
                    initial={{ opacity: 0, y: 15 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, x: -50, scale: 0.95 }}
                    transition={{ duration: 0.2 }}
                    className="group bg-card border border-border hover:border-primary/50 transition-all rounded-2xl p-6 shadow-sm hover:shadow-md relative overflow-hidden text-left"
                  >
                    {/* Background Glow */}
                    <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                    
                    <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 relative z-10">
                      <div className="flex items-start gap-4 flex-1">
                        <div className={`mt-1 w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${
                          rec.priority === 'High' ? 'bg-red-500/10 text-red-500' :
                          rec.priority === 'Medium' ? 'bg-amber-500/10 text-amber-500' :
                          'bg-blue-500/10 text-blue-500'
                        }`}>
                          <Lightbulb className="w-5 h-5" />
                        </div>
                        <div>
                          <div className="flex flex-wrap items-center gap-3 mb-2">
                            <h3 className="text-lg font-bold text-foreground">{rec.title}</h3>
                            <span className={`text-xs px-2.5 py-0.5 rounded-full font-semibold ${
                              rec.priority === 'High' ? 'bg-red-500/10 text-red-500 border border-red-500/20' :
                              rec.priority === 'Medium' ? 'bg-amber-500/10 text-amber-500 border border-amber-500/20' :
                              'bg-blue-500/10 text-blue-500 border border-blue-500/20'
                            }`}>
                              {rec.priority} Priority
                            </span>
                          </div>
                          <p className="text-foreground/70 leading-relaxed text-sm max-w-3xl">
                            {rec.description}
                          </p>
                          
                          <div className="flex items-center gap-6 mt-4">
                            <div className="flex items-center gap-1.5 text-sm font-semibold text-emerald-500">
                              <CheckCircle2 className="w-4 h-4" />
                              {recImpact}
                            </div>
                            <div className="flex items-center gap-1.5 text-sm text-foreground/50">
                              <Info className="w-4 h-4" />
                              {recConfidence}% AI Confidence
                            </div>
                          </div>
                        </div>
                      </div>
                      
                      <div className="flex md:flex-col items-center md:items-end justify-between gap-4 md:w-32 shrink-0 border-t md:border-t-0 md:border-l border-border pt-4 md:pt-0 md:pl-6">
                        <button 
                          onClick={() => handleApply(recId, rec.title)}
                          className="w-full py-2 px-4 bg-primary text-primary-foreground font-semibold rounded-xl text-sm shadow-lg shadow-primary/20 hover:bg-primary/90 transition-colors flex items-center justify-center gap-2 cursor-pointer"
                        >
                          Apply <ArrowRight className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => handleDismiss(recId, rec.title)}
                          className="text-sm font-semibold text-foreground/50 hover:text-foreground transition-colors cursor-pointer"
                        >
                          Dismiss
                        </button>
                      </div>
                    </div>
                  </motion.div>
                );
              })
            ) : (
              <div className="p-16 text-center text-foreground/50 flex flex-col items-center justify-center gap-2">
                <Inbox className="w-12 h-12 text-foreground/20" />
                <span className="text-base font-semibold">Workspace completely optimized!</span>
                <span className="text-sm text-foreground/40">Run another suggestions inference vector when needed.</span>
              </div>
            )}
          </AnimatePresence>
        </div>
      )}
      
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6 }}
        className="flex items-center justify-center p-8 text-foreground/40 text-sm gap-2"
      >
        <AlertTriangle className="w-4 h-4" />
        Recommendations are generated nightly based on the latest telemetry.
      </motion.div>
    </div>
  );
};

